package com.torqmind.ops.domain.voice;

public enum VoiceAction {
    CREATE_TASK,
    CREATE_OCCURRENCE,
    START_TASK,
    ADD_COMMENT,
    COMPLETE_TASK,
    REJECT_TASK,
    OPEN_TASK,
    OPEN_QUALITY_ANALYSIS,
    LIST_TASKS,
    LIST_OCCURRENCES,
    QUERY_TASK,
    DELETE_TASK,
    HELP,
    ADMIN_DENIED,
    START_OCCURRENCE,
    CLOSE_OCCURRENCE,
    LIST_MY_TASKS,
    OPEN_NOTIFICATIONS,
    SUMMARY_TODAY
}
